openapi: 3.2.0
info:
  contact:
    email: support@merqube.com
    name: API Support
    url: https://www.merqube.com/contact
  description: MerQube APIs
  title: MerQube API
  version: 4.40.0
servers:
- description: Production server
  url: https://api.merqube.com
- description: Testing server for next generation features
  url: https://api.staging.merqube.com
tags:
- name: api
paths:
  /api:
    get:
      description: serves this api in json format
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 200 response
      tags:
      - api
      summary: Get api
      x-summary-source: derived
      operationId: getApi
      x-operation-id-source: derived
x-internal: true
